SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
include $(SELF_DIR)common.mk
#
# Common repackage routines to be included in Makefiles
#
# The following variables are found in the sdk.mk file which is generated by the configure script:
# SDK_SRC_BASE		the base of the source code, typically the root of the cloned git repository
# SDK_BUILD_BASE	the base of the output
# JAVA_HOME			the base of the JDK used to build
A2_OUTPUT = $(SDK_BUILD_BASE)/a2
JVM ?= $(JAVA_HOME)/bin/java

# The following variables should be declared in the including Makefile:
# CATEGORIES		the space-separated list of categories to repackage

# The following variables have default values which can be overriden
# A2_BASE			the space-separated directories where already built a2 categories can be found
A2_BASE ?=/usr/share/a2 /usr/local/share/a2 $(A2_OUTPUT)

# Third-party libraries
LOGGER_JAR ?= $(lastword $(foreach base, $(A2_BASE), $(wildcard $(base)/org.argeo.tp/org.argeo.tp.syslogger.$(SYSLOGGER_BRANCH).jar)))
BNDLIB_JAR ?= $(lastword $(foreach base, $(A2_BASE), $(wildcard $(base)/org.argeo.tp.sdk/biz.aQute.bndlib.$(BNDLIB_BRANCH).jar)))

# Internal variables
TODOS_REPACKAGE = $(foreach category, $(CATEGORIES),$(BUILD_BASE)/$(category)/to-repackage) 
BUILD_BASE = $(SDK_BUILD_BASE)/$(shell basename $(SDK_SRC_BASE))

all: $(BUILD_BASE)/repackaged 

.SECONDEXPANSION:

# We use .SECONDEXPANSION and CATEGORIES_TO_REPACKAGE instead of directly CATEGORIES
# so that we don't repackage a category if it hasn't changed
$(BUILD_BASE)/repackaged : CATEGORIES_TO_REPACKAGE = $(subst $(abspath $(BUILD_BASE))/,, $(subst to-repackage,, $?))
$(BUILD_BASE)/repackaged : $(TODOS_REPACKAGE)
	$(JVM) \
	 -cp $(LOGGER_JAR):$(BNDLIB_JAR) \
	 $(SDK_SRC_BASE)/sdk/argeo-build/src/org/argeo/build/Repackage.java \
	 $(A2_OUTPUT) $(CATEGORIES_TO_REPACKAGE)
	touch $(BUILD_BASE)/repackaged

$(BUILD_BASE)/%/to-repackage : $$(shell find % -type f )
	@rm -rf $(dir $@)
	@mkdir -p $(dir $@) 
	@touch $@

clean:
	$(foreach category, $(CATEGORIES), rm -rf $(A2_OUTPUT)/$(category))
	$(foreach category, $(CATEGORIES), rm -rf $(BUILD_BASE)/$(category))
	rm -f $(BUILD_BASE)/repackaged
